Mappings:
  InstanceMap:
    eu-west-1:
      dev: t2.micro
      prod: m1.small
    us-west-1:
      dev: m1.small
      prod: m1.large
  AMIMap:
    eu-west-1:
      dev: ami-047bb4163c506cd98
      prod: ami-047bb4163c506cd98
    us-west-1:
      dev: ami-01c94064639c71719
      prod: ami-01c94064639c71719
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AMIMap, !Ref 'AWS::Region', dev]
      InstanceType: !FindInMap [InstanceMap, !Ref 'AWS::Region', dev]
